spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agileboard?currentSchema=agileboard
    username: postgres
    password: eljo

  jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop

server:
  port: 8889